### ISSUE TITLE
Fix my Github workflow ?

### ISSUE THREAD

**Issue by nchevobbe** [nchevobbe/gecko-dev#1]
Every time I create a new local feature branch, I have to do a full build, which is quite long ( 1 hour and a 
half ) on my laptop. Unfortunately, Artifact Builds doesn't seems to be available for git repo ( it is available with git-cinnabar and an hg repo ).

Here is what I did when I started the project : 
1. I forked mozilla/gecko-dev
2. cloned it on my laptop
3. added a remote to bgrins/gecko-dev 

```
bgrins  https://github.com/bgrins/gecko-dev (fetch)
bgrins  https://github.com/bgrins/gecko-dev (push)
```

And when I want to work on a new issue for bgrins/console-frontend, I do
1. `git fetch bgrins`
2. `git checkout -b feature bgrins/console-frontend`
3. `./mach build faster`

Usually, 6 tells me configuration has changed and I need a full build :/

@linclark , @bgrins , would you know what am I doing wrong ?

**Comment by linclark** [comment]
Really sorry to hear about this. 

I don't see the flaw in your workflow. It's the same one that I use. One thing that I do find... if I ever checkout `master` it will tell me I need a full build, even if I switch right back to the branch I was on without running any commands or doing anything on master.

**Comment by linclark** [comment]
Also, do you have a `.mozconfig` file set up? It wouldn't solve the problem, but if you set up caching in the config it might help with the time it takes to build. Brian has an [example one](https://gist.github.com/bgrins/de987fdbc018a884431b#file-mozconfig-normal).

**Comment by nchevobbe** [comment]
I do not have a mozconfig file, I'll set up one and see if it reduces the build time. Thanks Lin !

**Comment by bgrins** [comment]
I use a different repo altogether for this and my fx-team development (using hg for that).  I always wondered how people managed this with git.. I'd probably pull two clones of your fork if you have the hard drive space - one for normal m-c development and another for the console. But others might know a better way around it.

**Comment by linclark** [comment]
IIRC, @nchevobbe also uses separate repos for this and fx-team dev (he uses hg for fx-team) so I don't think that's it.

**Comment by nchevobbe** [comment]
Yep, I'm having a separate folder for my fx-team repo. Looks like greg is searching a way to have artifact build with git repo, maybe that'll bring a solution

**Comment by nchevobbe** [comment]
This issue was moved to nchevobbe/advent-of-code-2017#1
